stages:
  - build
  - deploy

build:
  stage: build
  image:  maven:3.6.1-jdk-8-slim
  script:
    - echo "Building app..."
    - mvn clean install
    - echo "Finished building the app."
  artifacts:
    expire_in: 1 week
    paths:
      - target/java-backend.service.jar

deploy:
  stage: deploy
  image: alpine:3.11
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying started..."
    - ssh ec2-user@$DEPLOY_SERVER_IP "sudo systemctl stop java-backend.service"
    - scp ./target/java-backend.service.jar ec2-user@$DEPLOY_SERVER_IP:~/java-backend.service/
    - ssh ec2-user@$DEPLOY_SERVER_IP "sudo systemctl start java-backend.service"
    - echo "Finished deploying the app."
  only:
    - Develop
    - master